// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuQb6kGkK2HZMb9xkYge0EdUV4cKY3Aqw',
    appId: '1:355316246511:web:2a9a45924c2f8c0f8af81a',
    messagingSenderId: '355316246511',
    projectId: 'nobot383',
    authDomain: 'nobot383.firebaseapp.com',
    storageBucket: 'nobot383.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrb-J9KqH1bk_5Wjoxpv2WI3usskefOC4',
    appId: '1:355316246511:android:ced87fda6b27717c8af81a',
    messagingSenderId: '355316246511',
    projectId: 'nobot383',
    storageBucket: 'nobot383.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2fjQopDVGMbiOoa7XJ4gcQWKBkl3aMRA',
    appId: '1:355316246511:ios:97e5168b895f09ae8af81a',
    messagingSenderId: '355316246511',
    projectId: 'nobot383',
    storageBucket: 'nobot383.firebasestorage.app',
    iosBundleId: 'com.example.nobot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2fjQopDVGMbiOoa7XJ4gcQWKBkl3aMRA',
    appId: '1:355316246511:ios:97e5168b895f09ae8af81a',
    messagingSenderId: '355316246511',
    projectId: 'nobot383',
    storageBucket: 'nobot383.firebasestorage.app',
    iosBundleId: 'com.example.nobot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuQb6kGkK2HZMb9xkYge0EdUV4cKY3Aqw',
    appId: '1:355316246511:web:88475976e7ee719f8af81a',
    messagingSenderId: '355316246511',
    projectId: 'nobot383',
    authDomain: 'nobot383.firebaseapp.com',
    storageBucket: 'nobot383.firebasestorage.app',
  );
}
